import { Metadata } from "next";

export const siteConfig = {
  name: "Instagram Video Download - Free Online Downloader",
  domain: "instagram-video-downloader.vercel.app",
  shortName: "IGDownloader",
  creator: "webtoolkit",
  description:
    "Easily perform an Instagram video download in HD, 4K. Our free online Instagram video downloader is fast, secure, and requires no login. Download reels, stories, and more.",
  ogDescription:
    "The best free online tool for Instagram video download. Save videos, reels, and stories in high quality. Fast, easy, and no login required.",
  url: "https://instagram-video-downloader.vercel.app",
  keywords: [
    "instagram video download",
    "instagram video downloader",
    "instagram video downloader online",
    "instagram video downloader without watermark",
    "instagram video downloader hd",
    "instagram video downloader 4k",
    "instagram video downloader mp4",
    "instagram video downloader app",
    "instagram video downloader apk",
    "instagram video downloader free",
    "instagram video downloader link",
    "private instagram video downloader",
    "instagram video downloader tool",
    "best instagram video downloader",
    "instagram reels downloader",
    "instagram reels download",
    "instagram reels video downloader",
    "hd instagram reels downloader",
    "instagram story downloader",
    "instagram story video downloader",
    "instagram highlight downloader",
    "instagram short video downloader",
    "instagram lite video downloader",
    "facebook video downloader",
    "facebook reels downloader",
    "tiktok video downloader",
    "snaptik video downloader",
    "snapinsta video downloader",
    "threads video downloader",
    "sss instagram video downloader",
    "gif maker online",
    "video cropper tool",
    "mp4 to mp3 converter",
    "yt-dlp downloader",
    "snap instagram video downloader",
    "how to download instagram videos",
    "instagram video downloader without login",
    "best free instagram video downloader app",
    "instagram private video downloader online",
    "download instagram videos in hd",
    "real instagram video downloader",
  ],
};

export const siteMetadata: Metadata = {
  title: {
    default: siteConfig.name,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  creator: siteConfig.creator,
  keywords: siteConfig.keywords,
  openGraph: {
    type: "website",
    locale: "en_US",
    title: siteConfig.name,
    description: siteConfig.ogDescription,
    url: siteConfig.url,
    siteName: siteConfig.name,
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.name,
    description: siteConfig.ogDescription,
    creator: siteConfig.creator,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: "/favicon.ico",
  },
  manifest: "/webmanifest.json",
};
